/* This file was initially auto-generated by https://github.com/pmndrs/gltfjsx and then adapted manually */
import React, { useState, useEffect, useRef } from "react";

import * as THREE from "three";
import { useGLTF, useAnimations } from "@react-three/drei";
import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader";
import { useLoader } from "@react-three/fiber";
// import m1 from "../../../../public/model/dance.gltf";

// useGLTF.preload("/model/shoe.gltf");
// useGLTF.preload(process.env.HOST + "/model/maximo/dance.gltf");
export default function ShoeApp({ color, ...props }) {
  const ref = useRef();
  // const gltf = useLoader(GLTFLoader, "/maximo/dance.gltf");
  const gltf = useGLTF("/model/maximo/dance.gltf");

  const animate = useAnimations(gltf.animations, ref);

  useEffect(() => {
    animate.actions["Armature|mixamo.com|Layer0"].play();
  }, []);

  return (
    <group ref={ref} shadows {...props} dispose={null}>
      <primitive object={gltf.scene} />
    </group>
  );
}
